// define all response code
const resCode = [
  { command: '100 - Continue' },
  { command: '101 - Switching Protocols' },
  { command: '102 - Processing' },
  { command: '200 - OK' },
  { command: '201 - Created' },
  { command: '202 - Accepted' },
  { command: '203 - Non-Authoritative Information' },
  { command: '204 - No Content' },
  { command: '205 - Reset Content' },
  { command: '206 - Partial Content' },
  { command: '300 - Multiple Choices' },
  { command: '301 - Moved Permanently' },
  { command: '302 - Found' },
  { command: '303 - See Other' },
  { command: '304 - Not Modified' },
  { command: '305 - Use Proxy' },
  { command: '306 - Unused' },
  { command: '307 - Temporary Redirect' },
  { command: '400 - Bad Request' },
  { command: '401 - Unauthorized' },
  { command: '402 - Payment Required' },
  { command: '403 - Forbidden' },
  { command: '404 - Not Found' },
  { command: '405 - Method Not Allowed' },
  { command: '406 - Not Acceptable' },
  { command: '407 - Proxy Authentication Required' },
  { command: '408 - Request Time-out' },
  { command: '409 - Conflict' },
  { command: '410 - Gone' },
  { command: '411 - Length Required' },
  { command: '412 - Precondition Failed' },
  { command: '413 - Request Entity Too Large' },
  { command: '414 - Request-URI Too Large' },
  { command: '415 - Unsupported Media Type' },
  { command: '416 - Requested range not satisfiable' },
  { command: '417 - Expectation Failed' },
  { command: '500 - Internal Server Error' },
  { command: '501 - Not Implemented' },
  { command: '502 - Bad Gateway' },
  { command: '503 - Service Unavailable' },
  { command: '504 - Gateway Time-out' },
  { command: '505 - HTTP Version not supported' },
];

export default resCode;
